{% set name = "gwcs" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60e4091ce02fc27a185bdec36bc1ea4da3ffa201d232746fda5fca8e6a2292a4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=3.6
    - astropy >=4.1
    - asdf
    - numpy
    - scipy

test:
  imports:
    - gwcs
    - gwcs.tags

about:
  home: https://gwcs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Generalized World Coordinate System
  description: |
    GWCS takes a general approach to WCS. It supports a data model which
    includes the entire transformation pipeline from input coordinates
    (detector by default) to world coordinates. Transformations can be
    chained, joined or combined with arithmetic operators using the flexible
    framework of compound models in astropy modeling. In the case of a
    celestial output frame coordinates provides further transformations
    between standard coordinate frames. Spectral output coordinates are
    instances of astropy Quantity and are transformed to other units with the
    tools in that package.
  doc_url: https://gwcs.readthedocs.io
  dev_url: https://github.com/spacetelescope/gwcs

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - nden
