{% set name = "gwcs" %}
{% set version = "0.22.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ac105d7b4f7730afc222df179f324e59cf3b92ee13aec7677eec6279197785a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base >=6.0
    - asdf >=3.3.0
    - numpy >=1.24
    - scipy >=1.14.1
    - asdf-wcs-schemas >=0.4.0
    - asdf-astropy >=0.5.0
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - gwcs

about:
  home: https://gwcs.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Generalized World Coordinate System
  description: |
    GWCS takes a general approach to WCS. It supports a data model which
    includes the entire transformation pipeline from input coordinates
    (detector by default) to world coordinates. Transformations can be
    chained, joined or combined with arithmetic operators using the flexible
    framework of compound models in astropy modeling. In the case of a
    celestial output frame coordinates provides further transformations
    between standard coordinate frames. Spectral output coordinates are
    instances of astropy Quantity and are transformed to other units with the
    tools in that package.
  doc_url: https://gwcs.readthedocs.io
  dev_url: https://github.com/spacetelescope/gwcs

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - nden
