travis:
  secure:
    BINSTAR_TOKEN: ITW38G//1nOPUhoFyURAhtee9KBgcI3F/xSr5IRk7GsSl3Fcn9dDdg2J55baOfKnBdiRHItLT6fB6EXdewEkoRLSXo2DohToUFLJwfk/z6ukLOJSOJUAlpNgzhWcX4pxPLplMazRYtJYC9/fmvuGezJuS0ytV87HW57bhcDhcFBqgnmjJrl3LarzBIacui8mBbPCjAKm5A9K7Xh0G69fzDdLXPjw5XM329jMruWOwRPATolssEU8KyfLQ0mtWxUoo/uaLhWtdQsLOEVuGym8m5E8ZhV85XtbHMZPAa7oXSkiZLEjfrruJvgAvFCYiHPajxS5+tv9TgDBpdQIGNLwR0V9Rw4mBqIRDaYVtah9+7/CDE07XER4CZ3uXsRzAmwE3RvqBUGGqR2dR4bHl/UPEHzzwWD55Gw1y6qdw9Na8hnZJadAxZqtiVphKEtSdvsOYY14+TUpvMw1X04rNoHvsayLQQyt1F4cByCMnS72IZ8vWWlGBhOHK9vhHXefU1QvtGtNFUZbXuNeKeVHq0h+JbcEakUWhR9peimh3CEqyKnXH6c2LHAPQgHV/16hjraNdB2ON8E/8vRieIBvJ9Kc7iQW94rYDVf+kyoQUrervbm1hd9Ze+92shbq5hLUYiuk0dMl6ezDKNhPfoL9FQUU8Sq15xep9FBLW91micTJ6Z4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
